### ISSUE TITLE
CLI should render nice tables for machines and machinesets

### ISSUE THREAD

**Issue by derekwaynecarr** [derekwaynecarr/openshift-the-easy-way#21]
See documentation as example:

https://github.com/derekwaynecarr/openshift-the-easy-way/blob/master/docs/compute/01-managing-compute.md#managing-compute

We should have nice table default renderings registered with our CLIs so we can surface nice information rather than jsonpath templates as you can see in linked doc.  Any chance we can get something quick before KubeCon?

@enxebre @ingvagabund @frobware @smarterclayton

**Comment by frobware** [comment]
> Any chance we can get something quick before KubeCon?

Sure, will take a look at the beginning of the week.

**Comment by derekwaynecarr** [comment]
it would be good if sets could at least mirror replica sets.  for machines, we may want formatters per platform type.  Example on amazon may want to show region, instance type, zone.

**Comment by frobware** [comment]
PR for machinesets: https://github.com/openshift/machine-api-operator/pull/148

**Comment by derekwaynecarr** [comment]
PRs have been merged for machine and sets
